version: 1
merge:
  trigger:
    labels:
      - 'pull: automerge'
    branches:
      - main
  ignore:
    labels:
      - 'pull: not merge'
      - 'approval: waiting'
    comment_substrings:
      - '==DO_NOT_MERGE=='
  method: squash
  options:
    squash:
      title: pull_request_title
      body: pull_request_body
  required_statuses:
    - Semantic PR
    - build-complete
    - specs-complete
    - license-complete
    - 'policy-bot: main'
    - lint (14.x)
    - terraform-plan
  delete_after_merge: true
update:
  trigger:
    labels:
      - 'pull: update'
    branches:
      - main
  ignore:
    labels:
      - 'pull: not update'
      - 'dependabot :rocket:'
