version: 1
merge:
  whitelist:
    labels: ["pull: automerge"]

  blacklist:
    labels: ["pull: not merge"]
    comment_substrings: ["==DO_NOT_MERGE=="]

  method: squash

  options:
    squash:
      # "title" defines how the title of the commit message is created when
      # generating a squash commit. The options are "pull_request_title",
      # "first_commit_title", and "github_default_title". The default is
      # "pull_request_title".
      title: "pull_request_title"

      # "body" defines how the body of the commit message is created when
      # generating a squash commit. The options are "pull_request_body",
      # "summarize_commits", and "empty_body". The default is "empty_body".
      body: "pull_request_body"

  required_statuses:
    - "Semantic PR"
    - "ci/circleci: build"
    - "ci/circleci: specs"
    - "ci/circleci: license"

  # If true, bulldozer will delete branches after their pull requests merge.
  delete_after_merge: true

# "update" defines how and when to update pull request branches. Unlike with
# merges, if this section is missing, bulldozer will not update any pull requests.
update:
  # "whitelist" defines the set of pull requests that should be updated by
  # bulldozer. It accepts the same keys as the whitelist in the "merge" block.
  whitelist:
    labels: ["pull: update"]

  # "blacklist" defines the set of pull requests that should not be updated by
  # bulldozer. It accepts the same keys as the blacklist in the "merge" block.
  blacklist:
    labels: ["pull: not update", "dependabot :rocket:"]
