version: 1
merge:
  trigger:
    labels:
      - 'pull: automerge'
    branches: []
  ignore:
    labels:
      - 'pull: not merge'
    comment_substrings:
      - '==DO_NOT_MERGE=='
  method: squash
  options:
    squash:
      title: pull_request_title
      body: pull_request_body
  required_statuses:
    - Semantic PR
    - build (14.x)
    - specs (12.x)
    - specs (14.x)
    - license (14.x)
  delete_after_merge: true
update:
  trigger:
    labels:
      - 'pull: update'
    branches:
      - master
  ignore:
    labels:
      - 'pull: not update'
      - 'dependabot :rocket:'
