name: Deploy assets to S3

on:
  repository_dispatch:
    types: [deploy]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

jobs:
  deploy_develop:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
      fail-fast: false

    steps:
      - name: Print Metadata
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Npm Dependencies
        run: npm ci

      - name: Build Sources
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy Assets
        run: $(npm bin)/tb s3 upload

      - name: Invalidate Cloudfront Distribution
        run: $(npm bin)/tb cf invalidate
