name: Labeled Issue by Assets
'on':
  issues:
    types:
      - labeled
jobs:
  move-to-do:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: >-
      startsWith(github.event.repository.name, 'assets_') &&
      github.event.label.name == 'bug' || github.event.label.name == 'support'
    env:
      TARGET_COLUMN: To do
    steps:
      - name: 'Try to move issue to ''${{ env.TARGET_COLUMN }}'''
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Team Assets
          column: '${{ env.TARGET_COLUMN }}'
          repo-token: '${{ secrets.TOKEN_GITHUB }}'
      - name: Wait on Error
        if: '${{ failure() }}'
        run: sleep 10
      - name: 'Retry to move issue to ''${{ env.TARGET_COLUMN }}'''
        uses: alex-page/github-project-automation-plus@v0.3.0
        if: '${{ failure() }}'
        with:
          project: Team Assets
          column: '${{ env.TARGET_COLUMN }}'
          repo-token: '${{ secrets.TOKEN_GITHUB }}'
