name: Private Deps Update
'on':
  schedule:
    - cron: 0 7 * * *
  push:
    branches:
      - master
    paths:
      - package.json
  repository_dispatch:
    types:
      - deps-update
env:
  PACKAGE_REGEX: '@otto-ec'
jobs:
  package-update:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.username != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2.3.4
        id: checkout
      - name: Fetch Branches and Tags
        id: fetch
        run: git fetch --prune --unshallow --tags
      - name: Configure git credentials
        id: credentials
        uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for Dependency Updates
        id: updater
        env:
          AUTHOR_EMAIL: fkt-assets-github@otto.de
          AUTHOR_NAME: FKT-assets-github
          EXECUTE: 'true'
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          LOG_LEVEL: debug
          UPDATE_COMMAND: npx
          PULL_REQUEST_TITLE: 'npm(priv): bump private otto-ec packages'
          BRANCH_PREFIX: deps-priv/
        run: >-
          npx actions-package-update npm-check-updates --packageFile
          package.json --dep dev,prod -u -f "/${{ env.PACKAGE_REGEX }}/"
          --loglevel verbose
