name: Ensure Semantic PR
'on':
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  lint_pr:
    name: Semantic PR
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            feat
            fix
            docs
            style
            refactor
            revert
            test
          requireScope: true
          subjectPattern: ^[a-z]+(\([a-z,*]+\))?:\s[^A-Z]+$
