name: Review Pull by Assets
'on':
  pull_request_target:
    types:
      - review_requested
      - review_request_removed
      - ready_for_review
jobs:
  check:
    runs-on: ubuntu-latest
    if: |-
      ${{
        github.event.pull_request.draft == false
        && !startsWith(github.event.pull_request.user.login, 'dependabot')
      }}
    outputs:
      requested: ${{ steps.reviews.outputs.requested }}
      reviews: ${{ steps.reviews.outputs.reviews }}
      approved: ${{ steps.reviews.outputs.approved }}
      changes_requested: ${{ steps.reviews.outputs.changes_requested }}
    steps:
      - name: Get Pull review info
        id: reviews
        uses: jurijzahn8019/action-get-pull-review-info@v0.0.21
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  to-review:
    runs-on: ubuntu-latest
    needs:
      - check
    if: |-
      ${{ 
        needs.check.outputs.requested > 0 
        || needs.check.outputs.reviews > 0
      }}
    steps:
      - name: Move Pull Request with Reviewers to 'Review / Approval'
        uses: alex-page/github-project-automation-plus@v0.7.1
        if: ${{ startsWith(github.event.repository.name, 'assets_') }}
        with:
          project: Team Assets
          column: Review / Approval
          repo-token: ${{ secrets.TOKEN_GITHUB }}
      - name: Add Pull Request Label for approval
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'approval: waiting'
      - name: Remove Pull Request Label for approval
        uses: actions-ecosystem/action-remove-labels@v1.1.1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'approval: submitted'
  to-progress:
    runs-on: ubuntu-latest
    needs:
      - check
    if: |-
      ${{ 
        needs.check.outputs.requested < 1 
        && needs.check.outputs.reviews < 1
      }}
    steps:
      - name: Move Pull Request without Reviewers to 'In Progress'
        uses: alex-page/github-project-automation-plus@v0.7.1
        if: ${{ startsWith(github.event.repository.name, 'assets_') }}
        with:
          project: Team Assets
          column: In Progress
          repo-token: ${{ secrets.TOKEN_GITHUB }}
      - name: Remove Pull Request Label for approval
        uses: actions-ecosystem/action-remove-labels@v1.1.1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            approval: waiting
            approval: submitted
