name: Review Pull by Assets
'on':
  pull_request_target:
    types:
      - review_requested
      - review_request_removed
      - ready_for_review
jobs:
  process:
    runs-on: ubuntu-latest
    if: >-
      startsWith(github.event.repository.name, 'assets_') &&
      github.event.pull_request.draft == false &&
      !startsWith(github.event.pull_request.user.login, 'dependabot')
    steps:
      - name: Calculate Reviewer Count
        id: revCount
        env:
          PRREVS: '${{ toJson(github.event.pull_request.requested_reviewers) }}'
        run: |
          REVCOUNT=$(echo $PRREVS | jq '.|length')
          echo "::set-output name=reviewers::$REVCOUNT"
      - name: Move Pull Request with Reviewers to 'Review / Approval'
        uses: alex-page/github-project-automation-plus@v0.3.0
        if: steps.revCount.outputs.reviewers > 0
        with:
          project: Team Assets
          column: Review / Approval
          repo-token: '${{ secrets.TOKEN_GITHUB }}'
      - name: Move Pull Request without Reviewers to 'In Progress'
        uses: alex-page/github-project-automation-plus@v0.3.0
        if: steps.revCount.outputs.reviewers < 1
        with:
          project: Team Assets
          column: In Progress
          repo-token: '${{ secrets.TOKEN_GITHUB }}'
      - name: Add Pull Request Label for approval
        uses: actions-ecosystem/action-add-labels@v1
        if: steps.revCount.outputs.reviewers > 0
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          labels: 'approval: waiting'
      - name: Remove Pull Request Label for approval
        uses: actions-ecosystem/action-remove-labels@v1
        continue-on-error: true
        if: steps.revCount.outputs.reviewers > 0
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          labels: 'approval: submitted'
      - name: Remove Pull Request Label for approval
        uses: actions-ecosystem/action-remove-labels@v1
        continue-on-error: true
        if: steps.revCount.outputs.reviewers < 1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          labels: |
            approval: waiting
            approval: submitted
