name: Approval Pull by Assets
'on':
  pull_request_review:
    types:
      - edited
      - dismissed
      - submitted
jobs:
  check:
    runs-on: ubuntu-latest
    if: >-
      github.event.pull_request.draft == false &&
      !startsWith(github.event.pull_request.user.login, 'dependabot')
    outputs:
      clear: ${{ steps.check.outputs.clear == 'true' }}
    steps:
      - name: Get Pull review info
        id: reviews
        uses: jurijzahn8019/action-get-pull-review-info@v0.0.25
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Clear Flag
        id: check
        if: |-
          ${{
            steps.reviews.outputs.requested < 1
            && steps.reviews.outputs.approved > 0
            && steps.reviews.outputs.changes_requested < 1
          }}
        run: echo "::set-output name=clear::true"
  process:
    runs-on: ubuntu-latest
    needs:
      - check
    if: ${{ needs.check.outputs.clear == 'true' }}
    steps:
      - name: Add Label when Approved
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'approval: submitted'
      - name: Remove Label when approved
        uses: actions-ecosystem/action-remove-labels@v1.1.1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'approval: waiting'
