name: Lint Pull Request

on:
  pull_request_target:
    types: [opened, edited, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint-changes:
    runs-on: ubuntu-latest

    steps:
      # Always checks out the target branch to not introduce insecure code from the PR that gets executed. This is done by default.
      #      - name: Checkout Sources from Pull
      #        uses: actions/checkout@v3
      #        id: checkout
      #      - name: Configure Node Runtime
      #        uses: actions/setup-node@v3
      #        id: setup_node
      #        with:
      #          node-version: 18.x
      #          cache: npm
      #      - name: Install Npm Dependencies
      #        id: npm_install
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      #        run: npm ci
      #
      #      - name: Lint PR Content if api specs are changed
      #        id: prlint
      #        run: npm run cli --silent -- guidelines-pull lint-changes

      - name: Lint PR Title if sources are changed
        uses: amannn/action-semantic-pull-request@v5.2.0
        if: ${{ steps.prlint.outputs.otherChanged == 'true' }}
        with:
          types: |
            chore
            feat
            fix
            docs
            style
            refactor
            revert
            test
            npm
            actions
            terraform
          requireScope: true
          subjectPattern: ^[^A-Z]+$
