name: Opened Pull by Assets
'on':
  pull_request_target:
    types:
      - opened
      - reopened
jobs:
  process:
    runs-on: ubuntu-latest
    if: >-
      startsWith(github.event.repository.name, 'assets_') &&
      !startsWith(github.event.pull_request.user.login, 'dependabot')
    steps:
      - name: Move new Pull Request in Progress
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Team Assets
          column: In Progress
          repo-token: '${{ secrets.TOKEN_GITHUB }}'
      - name: Add Label based on branch name
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
