name: Assigned Pull to Assets
'on':
  pull_request_target:
    types:
      - assigned
jobs:
  process:
    runs-on: ubuntu-latest
    if: >-
      !startsWith(github.event.repository.name, 'assets_') &&
      !startsWith(github.event.pull_request.user.login, 'dependabot')
    steps:
      - uses: jurijzahn8019/action-is-user-member-of-teams@v0.0.25
        id: checker
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          username: ${{ github.event.assignee.login }}
          teams: otto-ec/assets
      - name: Echo true
        if: ${{ steps.checker.outputs.ismember }}
        run: |
          echo "User is team Member"
          echo ${{ env.USER_IS_MEMBER }}
      - name: Move new Draft Pull Request in 'To do'
        uses: alex-page/github-project-automation-plus@v0.8.1
        if: >-
          steps.checker.outputs.ismember  && github.event.pull_request.draft ==
          true
        with:
          project: Team Assets
          column: To do
          repo-token: ${{ secrets.TOKEN_GITHUB }}
      - name: Move new Pull Request in Progress
        uses: alex-page/github-project-automation-plus@v0.8.1
        if: >-
          steps.checker.outputs.ismember  && github.event.pull_request.draft ==
          false
        with:
          project: Team Assets
          column: In Progress
          repo-token: ${{ secrets.TOKEN_GITHUB }}
