name: Approval Pull by Assets
'on':
  - pull_request_review
jobs:
  update-labels:
    runs-on: ubuntu-latest
    if: >-
      startsWith(github.event.repository.name, 'assets_') &&
      github.event.pull_request.draft == false &&
      !startsWith(github.event.pull_request.user.login, 'dependabot')
    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@v1.0.7
        env:
          APPROVALS: '1'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ADD_LABEL: 'approval: submitted'
          REMOVE_LABEL: 'approval:%20waiting'
