name: Pull Merge Cleanup
'on':
  schedule:
    - cron: 0 10 * * *
  repository_dispatch:
    types:
      - pulls-automerge
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: '!pull: not merge,!approval: waiting'
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: pull-request-title-and-description
          MERGE_DELETE_BRANCH: true
          MERGE_RETRIES: 2
          UPDATE_METHOD: rebase
