name: "Test automerge"

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "great"
      - name: envs
        uses: hmarr/debug-action@v2
