name: Terraform Deps Update
'on':
  schedule:
    - cron: 0 8 * * 1-5
  repository_dispatch:
    types:
      - deps-update
env:
  TOOLBOX: $(npm bin)/toolbox
jobs:
  terraform-update:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.username != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2.3.4
        id: checkout
      - name: Fetch Branches and Tags
        id: fetch
        run: git fetch --prune --unshallow --tags
      - uses: actions/setup-node@v2.1.4
        id: setup_node
        with:
          node-version: 14
      - name: setup cache for node
        uses: actions/cache@v2
        id: setup_cache_node
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14
      - name: Install Npm Dependencies
        id: npm_install
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: npm ci
      - name: Configure git credentials
        id: credentials
        uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS Credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Run Terraform Upgrade
        id: updater
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: ${{ env.TOOLBOX }} terraform upgrade --quiet
      - name: Create Commit
        run: |
          git add *.terraform.lock.hcl
          git -c author.name=FKT-assets-github \
          -c author.email=fkt-assets-github@otto.de \
          -c committer.name=FKT-assets-github \
          -c committer.email=fkt-assets-github@otto.de \
          commit \
          --no-verify \
          -m "update dependencies" \
          || true
      - name: Create Pull Request
        id: pull_request
        uses: peter-evans/create-pull-request@v3.8.0
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          committer: FKT-assets-github <fkt-assets-github@otto.de>
          author: FKT-assets-github <fkt-assets-github@otto.de>
          branch: deps-terraform/update
          title: 'terraform(deps): bump terraform dependencies'
